import {
  Armchair,
  Umbrella,
  Table2,
  Flame,
  Waves,
  Shirt,
  Bath,
  Sun,
  ShoppingBag,
  Volume2,
  Refrigerator,
  LifeBuoy,
  ParkingCircle,
  Wifi,
  Tv,
  ChefHat,
  WashingMachine,
  Wind,
  Utensils,
  TreePine,
  Tent,
} from "lucide-react";

export const poolFeatures = [
  { value: "camastros", label: "Camastros", icon: Armchair },
  { value: "sombrillas", label: "Sombrillas", icon: Umbrella },
  { value: "mesas", label: "Mesas", icon: Table2 },
  { value: "asador", label: "Asador", icon: Flame },
  { value: "regaderas", label: "Regaderas", icon: Waves },
  { value: "vestidores", label: "Vestidores", icon: Shirt },
  { value: "banos", label: "Baños", icon: Bath },
  { value: "palapa", label: "Palapa / Sombra", icon: Sun },
  { value: "hielera", label: "Hielera", icon: ShoppingBag },
  { value: "bocina", label: "Bocina(s)", icon: Volume2 },
  { value: "refrigerador", label: "Refrigerador", icon: Refrigerator },
  { value: "barra", label: "Barra", icon: Table2 },
  { value: "flotadores", label: "Flotadores", icon: LifeBuoy },
  { value: "sillas", label: "Sillas", icon: Armchair },
  { value: "estacionamiento", label: "Estacionamiento", icon: ParkingCircle },
  { value: "toallas", label: "Toallas", icon: Shirt },
];

export const cabinFeatures = [
  { value: "wifi", label: "WiFi", icon: Wifi },
  { value: "tv", label: "TV", icon: Tv },
  { value: "cocina", label: "Cocina", icon: ChefHat },
  { value: "lavadora", label: "Lavadora", icon: WashingMachine },
  { value: "refrigerador", label: "Refrigerador", icon: Refrigerator },
  { value: "ac", label: "A/C", icon: Wind },
  { value: "estacionamiento", label: "Estacionamiento", icon: ParkingCircle },
  { value: "sillones", label: "Sillones", icon: Armchair },
  { value: "microondas", label: "Microondas", icon: ChefHat },
  { value: "comedor", label: "Comedor", icon: Table2 },
  { value: "utensilios", label: "Utensilios de cocina", icon: Utensils },
  { value: "chimenea", label: "Chimenea", icon: Flame },
  { value: "bocina", label: "Bocina(s)", icon: Volume2 },
  { value: "toallas", label: "Toallas", icon: Shirt },
];

export const campingFeatures = [
  { value: "palapa", label: "Palapa / Sombra", icon: Sun },
  { value: "hielera", label: "Hielera", icon: ShoppingBag },
  { value: "bocina", label: "Bocina(s)", icon: Volume2 },
  { value: "estacionamiento", label: "Estacionamiento", icon: ParkingCircle },
  { value: "fogatero", label: "Fogatero", icon: Flame },
  { value: "lena", label: "Leña", icon: TreePine },
  { value: "mesas", label: "Mesas", icon: Table2 },
  { value: "asador", label: "Asador", icon: Flame },
];
